server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${APPLICATION_NAME}
  profiles.active: ${ACTIVE_PROFILE}
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: update
        hbm2ddl.auto: ${DDL_AUTO}
        naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #  jackson:
  #    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  #    serialization:
  #      indent_output: true
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

gateway:
  ip: ${GATEWAY_IP}