server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${APPLICATION_NAME}
  profiles.active: ${ACTIVE_PROFILE}
  #  jackson:
  #    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  #    serialization:
  #      indent_output: true
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: true


gateway:
  ip: ${GATEWAY_IP}

login:
  url:
    path: /auth/login